# Stage 1: Build the application
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

# Copy the pom.xml and source code
COPY pom.xml .
COPY src ./src

# Package the application (creates a jar file with dependencies)
RUN mvn clean package

# Stage 2: Create the lightweight runtime image
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# Copy the compiled JAR from the build stage
# Note: Adjust 'hello-world-1.0.jar' to match the actual jar name generated by your pom.xml
COPY --from=build /app/target/hello-world-1.0.jar ./app.jar

# Run the application
CMD ["java", "-jar", "app.jar"]
